apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-nodejs-deploy
  labels: 
    app: nodejs-app
spec:
  template:
  
      metadata:
        labels:
          app: nodejs-app
      spec:
        containers:
        - name: simple-nodejs-container
          image: ayush966/nodejs:0a2a3f2dc79256274ca7633e4a06fd069f963651
          ports:
          - containerPort: 3000
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-app   
