apiVersion: v1 
kind: Service
metadata:
  name: simple-nodejs-svc
  labels:
    app: nodejs-app
spec:
  type: NodePort
  ports:
  - port: 4000
    targetPort: 4000
    nodePort: 30500
  selector:
    app: nodejs-app